import * as Images from './ImportImage.js';


export const ReproductionsData = {
    France: [
        {
            id: 'france-1',
            image: Images.amur,
            artist: 'Марсель Руссо',
            title: 'Охота Амура',
            product: 'Холст, масло (50х80) ',
            price: 14500,
        },
        {
            id: 'france-2',
            image: Images.dog,
            artist: 'Анри Селин',
            title: 'Дама с собачкой',
            product: 'Акрил, бумага (50х80) ',
            price: 16500,
        },
        {
            id: 'france-3',
            image: Images.procedure,
            artist: 'Франсуа Дюпон',
            title: 'Процедура',
            product: 'Цветная литография (40х60)',
            price: 20000,
        },
        {
            id: 'france-4',
            image: Images.roze,
            artist: 'Луи Детуш',
            title: 'Роза',
            product: 'Бумага, акрил (50х80)',
            price: 12000,
        },
        {
            id: 'france-5',
            image: Images.birdie,
            artist: 'Франсуа Дюпон',
            title: 'Птичья трапеза',
            product: 'Цветная литография (40х60)',
            price: 22500,
        },
        {
            id: 'france-6',
            image: Images.LandscapeBird,
            artist: 'Пьер Моранж',
            title: 'Пейзаж с рыбой',
            product: 'Цветная литография (40х60)',
            price: 22000,
        },
    ],
    Germany: [
        {
            id: 'germany-1',
            image: Images.city,
            artist: 'Курт Вернер',
            title: 'Над городом',
            product: 'Цветная литография (40х60)',
            price: 16000,
        },
        {
            id: 'germany-2',
            image: Images.chicks,
            artist: 'Макс Рихтер',
            title: 'Птенцы',
            product: 'Холст, масло (50х80)',
            price: 14500,
        },
        {
            id: 'germany-3',
            image: Images.crane,
            artist: 'Мартин Майер',
            title: 'Среди листьев',
            product: 'Цветная литография (40х60)',
            price: 20000,
        },
        {
            id: 'germany-4',
            image: Images.bright,
            artist: 'Герман Беккер',
            title: 'Яркая птица',
            product: 'Цветная литография (40х60)',
            price: 13000,
        },
        {
            id: 'germany-5',
            image: Images.woodpecker,
            artist: 'Вульф Бауэр',
            title: 'Дятлы',
            product: 'Бумага, акрил (50х80)',
            price: 20000,
        },
        {
            id: 'germany-6',
            image: Images.bigWaters,
            artist: 'Вальтер Хартманн',
            title: 'Большие воды',
            product: 'Бумага, акрил (50х80)',
            price: 23000,
        },
    ],
    England: [
        {
            id: 'england-1',
            image: Images.moose,
            artist: 'Пол Смит',
            title: 'Дикий зверь',
            product: 'Акварель, бумага (50х80)',
            price: 19500,
        },
        {
            id: 'england-2',
            image: Images.rock,
            artist: 'Джон Уайт',
            title: 'Скалистый берег',
            product: 'Цветная литография (40х60)',
            price: 17500,
        },
        {
            id: 'england-3',
            image: Images.river,
            artist: 'Джим Уотсон',
            title: 'Река и горы',
            product: 'Акварель, бумага (50х80)',
            price: 20500,
        },
        {
            id: 'england-4',
            image: Images.parrot,
            artist: 'Юджин Зиллион',
            title: 'Белый попугай',
            product: 'Цветная литография (40х60)',
            price: 15500,
        },
        {
            id: 'england-5',
            image: Images.fish,
            artist: 'Эрик Гиллман',
            title: 'Ночная рыба',
            product: 'Бумага, акрил (50х80)',
            price: 12500,
        },
        {
            id: 'england-6',
            image: Images.cat,
            artist: 'Альфред Барр',
            title: 'Рыжий кот',
            product: 'Цветная литография (40х60)',
            price: 21000,
        },
    ]
}
